AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  DMSReplicationInstance:
    Type: String
    Default: 'arn:aws:dms:us-east-1:815363371634:rep:NTKOFPDB63TMKRR5TQIIEBSUBEXPTC6JIMLKIOY'
  DMSSourceEndpoint:
    Type: String
    Default: 'arn:aws:dms:us-east-1:815363371634:endpoint:TODGBXDWLENYABSJZJ4MNZPR4JIHPD2T5J2YYNQ'
  DMSTargetEndpoint:
    Type: String
    Default: 'arn:aws:dms:us-east-1:815363371634:endpoint:XDJ2CB2LH3HIT3EPU3NJEVIDB4YZYXENQ56RWEY'

Resources:
  DMSMigrationTask:
    Type: AWS::DMS::ReplicationTask
    Properties:
      ReplicationInstanceArn: !Ref DMSReplicationInstance
      SourceEndpointArn: !Ref DMSSourceEndpoint
      TargetEndpointArn: !Ref DMSTargetEndpoint
      MigrationType: full-load-and-cdc
      ReplicationTaskIdentifier: 'MySQLSourceTargetDemoTask'
      TableMappings: |
        {
          "rules": [
            {
              "rule-type": "selection",
              "rule-id": "1",
              "rule-name": "cryptocurrency_selection_rule",
              "object-locator": {
                "schema-name": "cryptocurrency",
                "table-name": "Wallets"
              },
              "rule-action": "include"
            }
          ]
        }
      ReplicationTaskSettings: |
        {
            "StreamBufferSettings": {
                "StreamBufferCount": 3,
                "CtrlStreamBufferSizeInMB": 5,
                "StreamBufferSizeInMB": 8
            },
            "ErrorBehavior": {
                "FailOnNoTablesCaptured": true,
                "ApplyErrorUpdatePolicy": "LOG_ERROR",
                "FailOnTransactionConsistencyBreached": false,
                "RecoverableErrorThrottlingMax": 1800,
                "DataErrorEscalationPolicy": "SUSPEND_TABLE",
                "ApplyErrorEscalationCount": 0,
                "RecoverableErrorStopRetryAfterThrottlingMax": true,
                "RecoverableErrorThrottling": true,
                "ApplyErrorFailOnTruncationDdl": false,
                "DataTruncationErrorPolicy": "LOG_ERROR",
                "ApplyErrorInsertPolicy": "LOG_ERROR",
                "EventErrorPolicy": "IGNORE",
                "ApplyErrorEscalationPolicy": "LOG_ERROR",
                "RecoverableErrorCount": -1,
                "DataErrorEscalationCount": 0,
                "TableErrorEscalationPolicy": "STOP_TASK",
                "RecoverableErrorInterval": 5,
                "ApplyErrorDeletePolicy": "IGNORE_RECORD",
                "TableErrorEscalationCount": 0,
                "FullLoadIgnoreConflicts": true,
                "DataErrorPolicy": "LOG_ERROR",
                "TableErrorPolicy": "SUSPEND_TABLE"
            },
            "TTSettings": {
                "TTS3Settings": null,
                "TTRecordSettings": null,
                "EnableTT": false
            },
            "FullLoadSettings": {
                "CommitRate": 10000,
                "StopTaskCachedChangesApplied": false,
                "StopTaskCachedChangesNotApplied": false,
                "MaxFullLoadSubTasks": 8,
                "TransactionConsistencyTimeout": 600,
                "CreatePkAfterFullLoad": false,
                "TargetTablePrepMode": "DO_NOTHING"
            },
            "TargetMetadata": {
                "ParallelApplyBufferSize": 0,
                "ParallelApplyQueuesPerThread": 0,
                "ParallelApplyThreads": 0,
                "TargetSchema": "",
                "InlineLobMaxSize": 0,
                "ParallelLoadQueuesPerThread": 0,
                "SupportLobs": true,
                "LobChunkSize": 0,
                "TaskRecoveryTableEnabled": false,
                "ParallelLoadThreads": 0,
                "LobMaxSize": 32,
                "BatchApplyEnabled": false,
                "FullLobMode": false,
                "LimitedSizeLobMode": true,
                "LoadMaxFileSize": 0,
                "ParallelLoadBufferSize": 0
            },
            "BeforeImageSettings": null,
            "ControlTablesSettings": {
                "historyTimeslotInMinutes": 5,
                "HistoryTimeslotInMinutes": 5,
                "StatusTableEnabled": false,
                "SuspendedTablesTableEnabled": false,
                "HistoryTableEnabled": false,
                "ControlSchema": "",
                "FullLoadExceptionTableEnabled": false
            },
            "LoopbackPreventionSettings": null,
            "CharacterSetSettings": null,
            "FailTaskWhenCleanTaskResourceFailed": false,
            "ChangeProcessingTuning": {
                "StatementCacheSize": 50,
                "CommitTimeout": 1,
                "BatchApplyPreserveTransaction": true,
                "BatchApplyTimeoutMin": 1,
                "BatchSplitSize": 0,
                "BatchApplyTimeoutMax": 30,
                "MinTransactionSize": 1000,
                "MemoryKeepTime": 60,
                "BatchApplyMemoryLimit": 500,
                "MemoryLimitTotal": 1024
            },
            "ChangeProcessingDdlHandlingPolicy": {
                "HandleSourceTableDropped": true,
                "HandleSourceTableTruncated": true,
                "HandleSourceTableAltered": true
            },
            "PostProcessingRules": null
        }


Host git-codecommit.*.amazonaws.com
  User APKA33V3RWJZC3HFVEUG
  IdentityFile ~/.ssh/CodeCommit1634