AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template for Secrets creating 

# Parameters:
#   Environment:
#     Type: String
#     Default: prod
#     AllowedValues:
#       - prod
#       - staging 

Resources:
  S000000010:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: /source/db/cryptocurrency/password
      GenerateSecretString:
        SecretStringTemplate: '{"username": "admin"}'
        GenerateStringKey: "password"
        PasswordLength: 20
        ExcludePunctuation: true
      Description: password

  S000000020:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: /dataprocessing/db/raw/password
      GenerateSecretString:
        SecretStringTemplate: '{"username": "admin"}'
        GenerateStringKey: "password"
        PasswordLength: 20
        ExcludePunctuation: true
      Description: password